### ISSUE TITLE
Separate the algorithm parameters from run config

### ISSUE THREAD

**Issue by hfattahi** [opera-adt/DSWX-SAR#6]
In oder to make it possible to more conveniently change the algorithm parameters in the SDS system without changing code and without redeployment of the system, we need to make a change to our run configs in all workflows. Since the change is a slight change to the interface, and we have a IF delivery, let's make this change to dswx-SAR. 
my suggestion is the following:

1- Take out all algorithm related parameters under [processing](https://github.com/opera-adt/DSWX-SAR/blob/main/src/dswx_sar/schemas/dswx_s1.yaml#L61) and write them to a separate file, and call it algorithm_parameters.yaml

2- add a new ancillary file to the run config [here](https://github.com/opera-adt/DSWX-SAR/blob/main/src/dswx_sar/schemas/dswx_s1.yaml#L12) called ```algorithm_parameters```

**Comment by oberonia78** [comment]
This issue was resolved.
